celery/django_celery/A/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

celery/django_celery/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
	path('', views.home, name='home'),
	path('<int:num_id>/', views.nums, name='nums'),
]

celery/django_celery/home/models.py
from django.db import models


class Number(models.Model):
	task_id = models.CharField(max_length=100)
	x = models.IntegerField()
	y = models.IntegerField()
	result = models.IntegerField(null=True, blank=True)

	def __str__(self):
		return f'{self.x} + {self.y} = {self.result}'

celery/django_celery/home/forms.py
from django import forms


class NumberForm(forms.Form):
	x = forms.IntegerField()
	y = forms.IntegerField()

celery/django_celery/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NumberForm
from .models import Number
from .tasks import adding


def home(request):
	numbers = Number.objects.all()
	if request.method == 'POST':
		form = NumberForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			num = Number(x=cd['x'], y=cd['y'])
			num.save()
			result = adding.delay(cd['x'], cd['y'], num.id)
			num.task_id = result.id
			num.save()
			return redirect('home:home')
	else:
		form = NumberForm()
	return render(request, 'home/home.html', {'form':form, 'numbers':numbers})


def nums(request, num_id):
	num = get_object_or_404(Number, id=num_id)
	return render(request, 'home/nums.html', {'num':num})

celery/django_celery/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <h4>Home</h4>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form><hr/>

    <div class="card">
        {% for number in numbers %}
            <a href="{% url 'home:nums' number.id %}" class="card-body">{{ number.x }} + {{ number.y }}</a>
        {% endfor %}
    </div>

{% endblock %}

celery/django_celery/home/templates/home/nums.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ num.x }} + {{ num.y }} = {{ num.result }}</h3>
{% endblock %}

celery/django_celery/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
    {% include 'inc/messages.html' %}
    {% block content %} {% endblock %}
    </div>

</body>
</html>

celery/django_celery/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

celery/django_celery/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'home:home' %}">Home</a>
    </div>
</nav>