django/class base view/mysite/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),   # way1
    path('login/', views.Login.as_view(template_name = 'accounts/login.html'), name='login')
]

django/class base view/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace='todo')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

django/class base view/mysite/todo/urls.py
from typing import Pattern
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.Hello.as_view(), name='todo_view'),
    # path('<int:pk>/', views.HelloDetail.as_view(), name='detail_view'),
    path('<slug:my_slug>/', views.HelloDetail.as_view(), name='detail_view'),
    path('add/create/', views.CreateForm.as_view(), name='create_form'),
    path('add/create/form/', views.CreateAddForm.as_view(), name='create_add_form'),
    path('delete/<int:pk>/', views.DeleteTodo.as_view(), name='delete_todo'),
    path('update/<int:pk>', views.UpdateTodo.as_view(), name='update_todo'),
]

django/class base view/mysite/accounts/models.py
from django.db import models

# Create your models here.

django/class base view/mysite/todo/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.title

django/class base view/mysite/todo/forms.py
from django import forms
from .models import Todo

class Todo_form(forms.Form):
    title = forms.CharField(max_length=200)

django/class base view/mysite/accounts/views.py
from django.contrib.auth import views as auth_views

class Login(auth_views.LoginView):
    template_name = 'accounts/login.html'

django/class base view/mysite/todo/views.py
from django.views import View
from django.views.generic.edit import DeleteView
from .models import Todo


'''View'''
'''به درد ویو های ساده میخوره'''
# class Hello(View):
#     def get(self, request, *args, **kwargs):
#         return render(request, 'todo/home.html')


from django.views.generic.base import TemplateView

'''TemplateView'''
'''امکان کوئری نوشتن را به ما میدهد'''
# class Hello(TemplateView):
#     template_name = 'todo/home.html'

#     def get_context_data(self, **kwargs):
#         contex = super().get_context_data(**kwargs)
#         contex['TODO'] = Todo.objects.all()
#         return contex


from django.views.generic.list import ListView
'''ListView'''
"""امکان این که بدون کوئری نوشتن یک لیست از یک مدل را به کاربر نشان دهیم"""
class Hello(ListView):
    template_name = 'todo/home.html'

    #query
    '''way1 : '''
    model = Todo

    '''way2 : '''
    queryset = Todo.objects.all() # object_list
    context_object_name = 'TODO'

    #ordering
    ordering = ['-created']


from django.views.generic.detail import DetailView
'''DetailView'''
"""امکان نشان دادن جزئیات هر پست را به کاربر میدهد اما فقط در یو ار ال میتواند ایدی یا اسلاگ دریافت کند"""
class HelloDetail(DetailView):
    model = Todo
    template_name = 'todo/home_detail.html'
    context_object_name = 'TODO'

    slug_field = 'slug'
    slug_url_kwarg = 'my_slug'


from django.views.generic import FormView
from .models import Todo
from .forms import Todo_form
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.contrib import messages
'''FormView'''
'''way1'''
class CreateForm(View):
    def get(self):
        pass
    def post(self):
        pass
'''way2'''
class CreateForm(FormView):
    form_class = Todo_form
    template_name = 'todo/create_home.html'
    success_url = reverse_lazy('todo:todo_view') #redirect in class base

    def form_valid(self, form):
        self.save_data(form.cleaned_data)
        return super().form_valid(form)

    def save_data(self, data):
        new_todo = Todo(title=data['title'], slug=slugify(data['title']))
        new_todo.save()
        messages.success(self.request, 'your todo added', 'success')



from django.views.generic import CreateView
'''CreateView'''
class CreateAddForm(CreateView):
    model = Todo
    fields = ['title']
    template_name = 'todo/create_home.html'
    success_url = reverse_lazy('todo:todo_view')

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.slug = slugify(form.cleaned_data['title'])
        todo.save()
        messages.success(self.request, 'your todo added', 'success')
        return super().form_valid(form)


from django.views.generic import DeleteView
'''DeleteView'''
'''به طور پیشفرض بجای ارسال کانتکس به اچ تی ام ال آبجکت ارسال میشود'''
class DeleteTodo(DeleteView):
    model = Todo
    template_name = 'todo/delete_todo.html'
    success_url = reverse_lazy('todo:todo_view')
    # context_object_name = 'TODO'


from django.views.generic import UpdateView
'''UpdateView'''
class UpdateTodo(UpdateView):
    model = Todo
    fields = ('title')
    template_name = 'todo/update_todo.html'
    success_url = reverse_lazy('todo:todo_view')

django/class base view/mysite/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>







    {% include 'inc/navbar.html' %}
    {% include 'inc/messages.html' %}
    <div class="jonbatram">
        {% block content %}{% endblock %}
    </div>







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
</body>

</html>

django/class base view/mysite/templates/inc/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% endif %}

django/class base view/mysite/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:todo_view' %}">logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>